// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AnalysisLine } from "./AnalysisLine";
import type { AnalysisState } from "./AnalysisState";
import type { NodeId } from "./NodeId";

/**
 * Payload of the `analysis://update` event: a snapshot of the analysis,
 * sent at most every 100 ms while the engine reports.
 */
export type AnalysisView = { state: AnalysisState, 
/**
 * The engine's configured name.
 */
engine: string | null, 
/**
 * The node being analysed.
 */
node: NodeId | null, 
/**
 * The move being searched for, e.g. `12s`.
 */
label: string | null, 
/**
 * The best line known for `node`: this search's, or a deeper one
 * stored from an earlier visit.
 */
line: AnalysisLine | null, 
/**
 * `line` is from an earlier visit; this search hasn't reached its depth.
 */
stored: boolean, 
/**
 * Engine output since the previous update.
 */
log: Array<string>, detail: string | null, };
