// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Eval } from "./Eval";
import type { NodeId } from "./NodeId";
import type { PvTurn } from "./PvTurn";

/**
 * What an engine has found about one node.
 */
export type AnalysisLine = { 
/**
 * The node analysed: the line starts from its position.
 */
node: NodeId, 
/**
 * As the engine writes it, e.g. `12+`.
 */
depth: string | null, eval: Eval | null, pv: Array<PvTurn>, nodes: number | null, timeMs: number | null, };
