// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AnimPiece } from "./AnimPiece";
import type { Color } from "./Color";
import type { Square } from "./Square";

/**
 * One step of an animation. Play in order: fade in `restored`, slide `id`
 * from `from` to `to`, then fade out `captured`.
 */
export type AnimStep = { id: number, from: Square, to: Square, captured: AnimPiece | null, restored: AnimPiece | null, 
/**
 * The side whose turn the step is in (a push moves the other side's
 * piece), so a capture can be told from losing one's own piece.
 */
mover: Color, };
