// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AnimPiece } from "./AnimPiece";
import type { Square } from "./Square";

/**
 * One step of an animation. Play in order: fade in `restored`, slide `id`
 * from `from` to `to`, then fade out `captured`.
 */
export type AnimStep = { id: number, from: Square, to: Square, captured: AnimPiece | null, restored: AnimPiece | null, };
