// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Piece } from "./Piece";
import type { Square } from "./Square";

/**
 * A piece appearing or disappearing during an animation.
 */
export type AnimPiece = { id: number, piece: Piece, square: Square, };
