// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ErrorKind } from "./ErrorKind";

/**
 * Error returned by commands.
 */
export type ApiError = { kind: ErrorKind, message: string, 
/**
 * 1-based record line, for `Record` errors.
 */
line: number | null, };
