// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a server bot's page says about it.
 */
export type BotInfoView = { about: string | null, 
/**
 * Whether it runs, and how many may at once, as its page says.
 */
status: string | null, 
/**
 * The time control of the games it opens.
 */
timeControl: string | null, rated: boolean | null, 
/**
 * Whether players may start it.
 */
canStart: boolean, };
