// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PieceKind } from "./PieceKind";

/**
 * Pieces of each color captured so far, strongest first.
 */
export type CapturedView = { gold: Array<PieceKind>, silver: Array<PieceKind>, };
