// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Color } from "./Color";

/**
 * A line of a gameroom game's chat.
 */
export type ChatLineView = { 
/**
 * Who wrote it, when the server says.
 */
side: Color | null, 
/**
 * The move it was written at (`6g`), when the server says.
 */
label: string | null, text: string, };
