// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Color } from "./Color";
import type { SideClockView } from "./SideClockView";

/**
 * Clock snapshot. The UI counts down locally from `turnElapsedMs` for the
 * running side.
 */
export type ClockView = { 
/**
 * Per side; `None` for an untimed side.
 */
gold: SideClockView | null, silver: SideClockView | null, 
/**
 * Side whose clock is running, if any.
 */
running: Color | null, 
/**
 * Time used so far on the running side's turn.
 */
turnElapsedMs: number, 
/**
 * Total time the running side may take this turn.
 */
turnAllowanceMs: number, 
/**
 * Time left before the game time limit, if there is one.
 */
gameRemainingMs: number | null, 
/**
 * Worked out for the shown move from the move times and the time
 * control, rather than the live clock.
 */
past: boolean, };
