// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Color } from "./Color";

/**
 * Clock snapshot. The UI counts down locally from `turnElapsedMs` for the
 * running side.
 */
export type ClockView = { timeControl: string, moveTimeMs: number, goldReserveMs: number, silverReserveMs: number, 
/**
 * Side whose clock is running, if any.
 */
running: Color | null, 
/**
 * Time used so far on the running side's turn.
 */
turnElapsedMs: number, 
/**
 * Total time the running side may take this turn.
 */
turnAllowanceMs: number, };
