// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A configured engine.
 */
export type EngineSpec = { 
/**
 * Stable id; empty when adding a new engine.
 */
id: string, name: string, program: string, args: Array<string>, workingDir: string | null, };
