// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EngineOption } from "./EngineOption";
import type { InstalledFrom } from "./InstalledFrom";

/**
 * A configured engine.
 */
export type EngineSpec = { 
/**
 * Stable id; empty when adding a new engine.
 */
id: string, name: string, program: string, args: Array<string>, workingDir: string | null, 
/**
 * Sent with `setoption` after the handshake, for play and analysis
 * (`threads`, `hash`, ...). They override the options the app sets for
 * a known engine.
 */
options: Array<EngineOption>, 
/**
 * The manifest release it was installed from, if any.
 */
installed?: InstalledFrom, };
