// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Color } from "./Color";
import type { EngineOutputKind } from "./EngineOutputKind";

/**
 * Payload of the `engine://output` event.
 */
export type EngineOutput = { side: Color, kind: EngineOutputKind, 
/**
 * Display text, e.g. `depth 12+` or the log line.
 */
text: string, depth: string | null, score: number | null, pv: Array<string> | null, };
