// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What an engine reported about itself in the handshake.
 */
export type EngineIdentity = { name: string | null, author: string | null, version: string | null, protocolVersion: number, };
