// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One engine option, as `setoption name <name> value <value>` sends it.
 */
export type EngineOption = { name: string, value: string, };
