// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ManifestView } from "./ManifestView";
import type { SuggestedEngine } from "./SuggestedEngine";

/**
 * The engine manifests the user has added, and the suggested ones not
 * added yet.
 */
export type EngineCatalogView = { 
/**
 * This computer's platform, as manifests name it (`linux-x86_64`).
 */
platform: string, manifests: Array<ManifestView>, suggested: Array<SuggestedEngine>, };
