// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InvitationView } from "./InvitationView";
import type { LiveGameView } from "./LiveGameView";
import type { RecentGameView } from "./RecentGameView";

/**
 * The gameroom's game lists.
 */
export type GameroomGames = { 
/**
 * Who the lists are for: the logged-in user.
 */
user: string | null, live: Array<LiveGameView>, 
/**
 * The last few games finished, newest first.
 */
recent: Array<RecentGameView>, 
/**
 * The user's games: ones they created, waiting for an opponent, and
 * ones they play.
 */
mine: Array<LiveGameView>, 
/**
 * Games others created, with a seat to take.
 */
open: Array<LiveGameView>, 
/**
 * Open invitations, to the user and from them.
 */
invitations: Array<InvitationView>, };
