// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LiveGameView } from "./LiveGameView";
import type { RecentGameView } from "./RecentGameView";

/**
 * The gameroom's game lists.
 */
export type GameroomGames = { live: Array<LiveGameView>, 
/**
 * The last few games finished, newest first.
 */
recent: Array<RecentGameView>, 
/**
 * The user's games: ones they created, waiting for an opponent, and
 * ones they play.
 */
mine: Array<LiveGameView>, 
/**
 * Games others created, with a seat to take.
 */
open: Array<LiveGameView>, };
