// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The arimaa.com gameroom login.
 */
export type GameroomStatus = { 
/**
 * Who is logged in, if anyone: their gameroom username, also when
 * they logged in with their email address.
 */
username: string | null, 
/**
 * The name of the remembered login (a username or email address), if one is saved (its password
 * stays in the backend).
 */
savedUsername: string | null, };
