// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Color } from "./Color";
import type { WinReason } from "./WinReason";

export type GameResult = { winner: Color, reason: WinReason, };
