// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LiveGameView } from "./LiveGameView";
import type { RecentGameView } from "./RecentGameView";

/**
 * The gameroom's game lists.
 */
export type GameroomGames = { live: Array<LiveGameView>, 
/**
 * The last few games finished, newest first.
 */
recent: Array<RecentGameView>, };
