// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The arimaa.com gameroom login.
 */
export type GameroomStatus = { 
/**
 * Who is logged in, if anyone.
 */
username: string | null, 
/**
 * The username of the remembered login, if one is saved (its password
 * stays in the backend).
 */
savedUsername: string | null, };
