// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which manifest release an engine was installed from.
 */
export type InstalledFrom = { 
/**
 * The manifest's `id`.
 */
manifest: string, version: string, };
