// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InvitationOutcome } from "./InvitationOutcome";

/**
 * How an invitation the user sent was answered, sent as
 * `gameroom://invitation`.
 */
export type InvitationAnswer = { opponent: string, outcome: InvitationOutcome, };
