// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Color } from "./Color";

/**
 * An open invitation to play, to the user (`incoming`) or from them.
 */
export type InvitationView = { incoming: boolean, 
/**
 * The other player's username and rating.
 */
opponent: string | null, opponentRating: string | null, 
/**
 * The side the user would play.
 */
side: Color, timeControl: string | null, rated: boolean, 
/**
 * The inviter's message.
 */
message: string | null, 
/**
 * The other player's id and when it was sent, which name the
 * invitation in the accept, decline and cancel commands.
 */
otherId: string, created: string, };
