// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Color } from "./Color";

export type InvitationOutcome = { "kind": "accepted", gid: string, side: Color, } | { "kind": "declined", message: string, } | { "kind": "gone" };
