// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Color } from "./Color";
import type { LastStepView } from "./LastStepView";

/**
 * The move that produced the shown position, for the last-move display.
 */
export type LastMoveView = { color: Color, steps: Array<LastStepView>, };
