// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Piece } from "./Piece";
import type { PieceAt } from "./PieceAt";
import type { Square } from "./Square";

/**
 * One step of the move that produced the shown position.
 */
export type LastStepView = { 
/**
 * The piece that stepped; an enemy of the mover when pushed or pulled.
 */
piece: Piece, from: Square, to: Square, 
/**
 * A piece captured on a trap as a result of this step.
 */
captured: PieceAt | null, };
