// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A game being played on arimaa.com, from the gameroom's live list.
 */
export type LiveGameView = { gid: string, gold: string | null, silver: string | null, timeControl: string | null, rated: boolean, postal: boolean, };
