// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A game in one of the gameroom's lists: being played, open for a
 * player to sit, or the user's own. A free seat has no player.
 */
export type LiveGameView = { gid: string, gold: string | null, silver: string | null, timeControl: string | null, rated: boolean, postal: boolean, };
