// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ManifestOptionView } from "./ManifestOptionView";

/**
 * An engine manifest the user added.
 */
export type ManifestView = { id: string, name: string, 
/**
 * The release this manifest describes.
 */
version: string, author: string | null, description: string | null, homepage: string | null, license: string | null, 
/**
 * Where it was fetched from (none for a file).
 */
source: string | null, 
/**
 * Whether it says where updates are (or came from a URL).
 */
updatable: boolean, 
/**
 * Whether it has a download for this computer.
 */
downloadable: boolean, 
/**
 * The version installed from it, and that engine's id.
 */
installedVersion: string | null, engineId: string | null, options: Array<ManifestOptionView>, };
