// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An option a manifest describes.
 */
export type ManifestOptionView = { name: string, 
/**
 * `check`, `spin`, `float`, `combo`, `string`, `file`, `path` or `button`.
 */
kind: string, 
/**
 * The default as `setoption` would send it.
 */
default: string | null, min: number | null, max: number | null, choices: Array<string>, description: string | null, };
