// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlayerSpec } from "./PlayerSpec";

export type MatchSpec = { gold: PlayerSpec, silver: PlayerSpec, 
/**
 * Arimaa time control per side, e.g. `30s/5m`; `None` leaves that side
 * untimed.
 */
goldTimeControl: string | null, silverTimeControl: string | null, };
