// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MoveView = { 
/**
 * Ply after this move; `goto_ply(ply)` shows the position it produced.
 */
ply: number, 
/**
 * Move number label, e.g. `2g`.
 */
label: string, notation: string, };
