// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AnimStep } from "./AnimStep";
import type { PieceView } from "./PieceView";

/**
 * What the board needs to replay the move that produced the shown position.
 */
export type MoveReplay = { 
/**
 * Pieces before the move.
 */
before: Array<PieceView>, animation: Array<AnimStep>, };
