// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GameResult } from "./GameResult";
import type { NodeId } from "./NodeId";

/**
 * One move of the game tree, as the move list shows it. `SessionView.tree`
 * lists them in display order: each main move, then the variations that
 * replace it (and continuations after a line's last move), nested.
 */
export type MoveNodeView = { id: NodeId, parent: NodeId, 
/**
 * Ply after this move.
 */
ply: number, 
/**
 * Nesting: 0 on the main line, one more per level of variation.
 */
depth: number, 
/**
 * The first move of a variation.
 */
startsVariation: boolean, 
/**
 * How many variations end with this move (nested ones can end
 * together).
 */
closes: number, 
/**
 * Move number label, e.g. `2g`.
 */
label: string, notation: string, 
/**
 * Annotation glyphs as written (`!?`, `$14`).
 */
glyphs: Array<string>, comment: string | null, 
/**
 * Introduction to the variation this move starts.
 */
intro: string | null, 
/**
 * On the line being shown.
 */
onLine: boolean, 
/**
 * How the game ended at this move, if it did.
 */
result: GameResult | null, 
/**
 * The first move of a variation with more moves after it, which can
 * be folded.
 */
collapsible: boolean, 
/**
 * While folded, how many moves of the variation are hidden after this
 * one (0 when it's open).
 */
folded: number, };
