// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GameResult } from "./GameResult";

/**
 * A game from a player's past games.
 */
export type PastGameView = { 
/**
 * The permanent id.
 */
gid: string, gold: string, silver: string, 
/**
 * The players' ratings now, not at the time of the game.
 */
goldRating: string | null, silverRating: string | null, timeControl: string | null, rated: boolean, result: GameResult | null, 
/**
 * The last move's number.
 */
moves: number | null, 
/**
 * When it finished, as the server writes it.
 */
finished: string | null, };
