// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Piece } from "./Piece";
import type { Square } from "./Square";

export type PieceView = { id: number, piece: Piece, square: Square, frozen: boolean, };
