// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Color } from "./Color";
import type { PieceKind } from "./PieceKind";

export type Piece = { color: Color, kind: PieceKind, };
