// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Piece kinds, ordered weakest to strongest so `Ord` compares strength.
 */
export type PieceKind = "rabbit" | "cat" | "dog" | "horse" | "camel" | "elephant";
