// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlayerKind } from "./PlayerKind";

export type PlayerView = { kind: PlayerKind, name: string, };
