// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EngineOption } from "./EngineOption";
import type { PlayerKind } from "./PlayerKind";

export type PlayerView = { kind: PlayerKind, name: string, 
/**
 * An engine's id in the engine list.
 */
engineId: string | null, 
/**
 * An engine's options for this game only, over its saved ones.
 */
options: Array<EngineOption>, };
