// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A player choice when starting a game.
 */
export type PlayerSpec = { "kind": "human" } | { "kind": "engine", engineId: string, };
