// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PastGameView } from "./PastGameView";

/**
 * A page of a player's past games, newest first.
 */
export type PlayerGamesView = { games: Array<PastGameView>, 
/**
 * The offset of the next (older) page, if there is one.
 */
next: number | null, };
