// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A player found by the gameroom's player search.
 */
export type PlayerMatchView = { 
/**
 * The player id, which the player's games are asked for by.
 */
id: string, username: string, 
/**
 * The real name the player gave.
 */
name: string | null, };
