// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlayerView } from "./PlayerView";

export type PlayersView = { gold: PlayerView, silver: PlayerView, };
