// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EngineOption } from "./EngineOption";

/**
 * A player choice when starting a game.
 */
export type PlayerSpec = { "kind": "human" } | { "kind": "engine", engineId: string, 
/**
 * Options for this game only, sent over the engine's saved ones.
 */
options?: Array<EngineOption>, };
