// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Square } from "./Square";

export type PositionProblemView = { message: string, 
/**
 * The squares it's about, to mark on the board.
 */
squares: Array<Square>, };
