// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Color } from "./Color";
import type { PieceView } from "./PieceView";

export type PositionView = { sideToMove: Color, pieces: Array<PieceView>, 
/**
 * AEI short format, handy for debugging and engine hand-off.
 */
short: string, };
