// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Color } from "./Color";

/**
 * A set position (position editor): the board in AEI's short format, the
 * side to move and the move number, so `2g` is the first turn after the
 * setups.
 */
export type PositionSpec = { 
/**
 * `[` + 64 squares from a8 to h1 + `]`, a space for an empty square.
 */
short: string, sideToMove: Color, moveNumber: number, };
