// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PositionProblemView } from "./PositionProblemView";

/**
 * What the position editor shows about a position: what keeps it from
 * starting a game, and the position in both formats.
 */
export type PositionCheck = { problems: Array<PositionProblemView>, 
/**
 * The short format with the side to move, `g [...]`, as the record's
 * `Position` tag and AEI's `setposition` take it.
 */
short: string, 
/**
 * The long format: the move label, then the board diagram.
 */
long: string, 
/**
 * As two setup moves (`1g ...`, `1s ...`, and `2g pass` for silver to
 * move), as arimaa.com's puzzle viewer writes positions.
 */
setup: string, 
/**
 * The first move's label, e.g. `2g`.
 */
label: string, 
/**
 * How many pieces of each kind each side has left to place, by
 * piece letter (`E`, `m`, ...); negative when there are too many.
 */
left: Array<[string, number]>, };
