// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A postal game being played on arimaa.com, from the gameroom's postal
 * games page.
 */
export type PostalGameView = { 
/**
 * The gameroom id, to watch it by.
 */
gid: string, gold: string, silver: string, goldRating: string | null, silverRating: string | null, timeControl: string | null, rated: boolean, };
