// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PuzzleEntryView } from "./PuzzleEntryView";

/**
 * A heading of arimaa.com's puzzle list and its puzzles.
 */
export type PuzzleGroupView = { name: string, puzzles: Array<PuzzleEntryView>, };
