// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Color } from "./Color";
import type { PuzzleStatus } from "./PuzzleStatus";

/**
 * A puzzle being solved: its question, and how the solving goes.
 */
export type PuzzleView = { 
/**
 * arimaa.com's puzzle id (`p4`), for one from its puzzle pages.
 */
id: string | null, title: string | null, 
/**
 * What to do, such as "Gold to move and win in two".
 */
question: string | null, 
/**
 * The side the solver plays.
 */
solver: Color, status: PuzzleStatus, 
/**
 * Whether the puzzle came with its solution, to check moves against.
 */
hasSolution: boolean, 
/**
 * The solver's moves left in the solution.
 */
movesLeft: number, 
/**
 * The position the solver's next move is expected from is shown.
 */
atFrontier: boolean, 
/**
 * The hint, once asked for (empty when the puzzle has none).
 */
hint: string | null, 
/**
 * Whether a hint can be asked for (arimaa.com's puzzles have one).
 */
hintAvailable: boolean, author: string | null, 
/**
 * The last move tried that isn't the solution, as `2g Ee2n ...`.
 */
wrongMove: string | null, };
