// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PuzzleEntryView = { 
/**
 * arimaa.com's id, such as `p4`.
 */
id: string, title: string, };
