// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LastMoveView } from "./LastMoveView";

/**
 * One turn of an engine's principal variation, checked to be legal.
 */
export type PvTurn = { 
/**
 * Move number label, e.g. `12s`.
 */
label: string, 
/**
 * In normal form, with capture tokens.
 */
notation: string, 
/**
 * The steps, for drawing (`None` for a setup).
 */
steps: LastMoveView | null, };
