// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GameResult } from "./GameResult";

/**
 * A game recently finished on arimaa.com, from the gameroom's list.
 */
export type RecentGameView = { 
/**
 * The permanent id.
 */
gid: string, gold: string | null, silver: string | null, goldRating: string | null, silverRating: string | null, timeControl: string | null, rated: boolean, postal: boolean, result: GameResult | null, 
/**
 * The last move's number (`5` for a game ending at 5b).
 */
moves: number | null, 
/**
 * When it ended, in milliseconds since the Unix epoch.
 */
endedMs: number | null, };
