// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ServerBotView } from "./ServerBotView";

/**
 * The server's bots, and the official bot ladder among them.
 */
export type ServerBotsView = { 
/**
 * Every bot, in the order of the server's list.
 */
bots: Array<ServerBotView>, 
/**
 * The official bot ladder's bots (`ServerBotView.name`), highest
 * first; empty if arimaa.com didn't give it.
 */
ladder: Array<string>, 
/**
 * How many of `ladder` are above the user (not beaten yet); the user
 * stands between them and the rest.
 */
ladderAbove: number, };
