// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A bot arimaa.com runs, which anyone can start a game against.
 */
export type ServerBotView = { 
/**
 * Its username (`bot_…`).
 */
name: string, rating: number | null, 
/**
 * The rating's uncertainty (30 the most accurate, 120 the least).
 */
ratingUncertainty: number | null, 
/**
 * Its control page, which `start_gameroom_bot` takes.
 */
page: string, 
/**
 * Whether the user has yet to beat it (the bot ladder's "To be won");
 * none if arimaa.com didn't give the user's record.
 */
toBeWon: boolean | null, 
/**
 * The user's games against it, won and lost, once they've played it.
 */
games: number | null, won: number | null, lost: number | null, };
