// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AnimStep } from "./AnimStep";
import type { SessionView } from "./SessionView";

/**
 * Payload of the `game://changed` event: the new state, plus the steps to
 * animate from the previous state (empty means snap).
 */
export type SessionUpdate = { view: SessionView, animation: Array<AnimStep>, };
