// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AnalysisLine } from "./AnalysisLine";
import type { CapturedView } from "./CapturedView";
import type { ClockView } from "./ClockView";
import type { Color } from "./Color";
import type { GameResult } from "./GameResult";
import type { LastMoveView } from "./LastMoveView";
import type { MoveNodeView } from "./MoveNodeView";
import type { MoveView } from "./MoveView";
import type { NodeId } from "./NodeId";
import type { Phase } from "./Phase";
import type { PlayersView } from "./PlayersView";
import type { PositionView } from "./PositionView";
import type { TurnView } from "./TurnView";

export type SessionView = { 
/**
 * The line being shown, one entry per move.
 */
moves: Array<MoveView>, 
/**
 * Every move of the game tree, in display order.
 */
tree: Array<MoveNodeView>, 
/**
 * The comment on the whole game (before the first move).
 */
gameComment: string | null, 
/**
 * The node being shown (the root before any move).
 */
cursor: NodeId, 
/**
 * In a match, the live node: the end of the game being played.
 */
live: NodeId | null, 
/**
 * Ply being shown (0 = empty board, `moves.len()` = latest).
 */
ply: number, phase: Phase, 
/**
 * Position at `ply`, including any in-progress turn or setup draft.
 */
position: PositionView, 
/**
 * Present while a turn is being entered.
 */
turn: TurnView | null, 
/**
 * The move that produced the position at `ply`, unless it was a setup.
 */
lastMove: LastMoveView | null, 
/**
 * Pieces captured up to `ply`, including in the turn being entered.
 */
captured: CapturedView, 
/**
 * Moves after `ply` on the line being shown.
 */
movesAfterCursor: number, result: GameResult | null, endMarker: string | null, 
/**
 * Why the game ended, when it wasn't on the board (illegal engine move,
 * engine crash, ...).
 */
endDetail: string | null, 
/**
 * Present during a match (a game with an engine or a clock).
 */
players: PlayersView | null, 
/**
 * The players' names from the record's `Gold` and `Silver` tags (a
 * loaded game's players), for when there's no match.
 */
tagNames: [string | null, string | null], clock: ClockView | null, 
/**
 * The side whose engine is thinking.
 */
thinking: Color | null, 
/**
 * Whether board input is accepted now: any time outside a match; in a
 * match, moves anywhere (as plans) but setups only on a human's turn.
 */
canInput: boolean, 
/**
 * Whether committing now plays a move in the match (a human's turn at
 * the live position), rather than adding a variation.
 */
playsLive: boolean, 
/**
 * The plan move Enter would play (`3g Ee2n …`), when the cursor is in
 * a plan for the user's move.
 */
planMove: string | null, 
/**
 * In a match, the latest move played (`3s ed7s …`), if any.
 */
liveMove: string | null, 
/**
 * Whether Undo step (Backspace) has something to undo: a step, the
 * move into the shown position, or a takeback.
 */
canUndo: boolean, 
/**
 * Whether played moves can be taken back now (a match with takebacks,
 * shown at the live position).
 */
canTakeBack: boolean, 
/**
 * In a match, the ply of the live position if it's on the line being
 * shown.
 */
livePly: number | null, 
/**
 * The engine analysing the shown position, while analysis is on.
 */
analysisEngine: string | null, 
/**
 * What analysis found at the shown node earlier, if anything, so the
 * eval shows at once while the new search starts.
 */
storedAnalysis: AnalysisLine | null, };
