// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Identifies one of the backend's sessions (a game shown in a window).
 * Every session command takes one, and session events carry it as a
 * `session` field.
 */
export type SessionId = number;
