// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GameResult } from "./GameResult";
import type { MoveView } from "./MoveView";
import type { Phase } from "./Phase";
import type { PositionView } from "./PositionView";
import type { TurnView } from "./TurnView";

export type SessionView = { moves: Array<MoveView>, 
/**
 * Ply being shown (0 = empty board, `moves.len()` = latest).
 */
ply: number, phase: Phase, 
/**
 * Position at `ply`, including any in-progress turn or setup draft.
 */
position: PositionView, 
/**
 * Present while a turn is being entered.
 */
turn: TurnView | null, 
/**
 * Moves that committing now would discard (when entering a move before the end).
 */
movesAfterCursor: number, result: GameResult | null, endMarker: string | null, };
