// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClockView } from "./ClockView";
import type { Color } from "./Color";
import type { GameResult } from "./GameResult";
import type { MoveView } from "./MoveView";
import type { Phase } from "./Phase";
import type { PlayersView } from "./PlayersView";
import type { PositionView } from "./PositionView";
import type { TurnView } from "./TurnView";

export type SessionView = { moves: Array<MoveView>, 
/**
 * Ply being shown (0 = empty board, `moves.len()` = latest).
 */
ply: number, phase: Phase, 
/**
 * Position at `ply`, including any in-progress turn or setup draft.
 */
position: PositionView, 
/**
 * Present while a turn is being entered.
 */
turn: TurnView | null, 
/**
 * Moves that committing now would discard (when entering a move before the end).
 */
movesAfterCursor: number, result: GameResult | null, endMarker: string | null, 
/**
 * Why the game ended, when it wasn't on the board (illegal engine move,
 * engine crash, ...).
 */
endDetail: string | null, 
/**
 * Present during a match (a game with an engine or a clock).
 */
players: PlayersView | null, clock: ClockView | null, 
/**
 * The side whose engine is thinking.
 */
thinking: Color | null, 
/**
 * Whether board input is accepted now (a human's turn at the live end
 * of a match, or any time outside a match).
 */
canInput: boolean, };
