// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionId } from "./SessionId";

/**
 * The sessions open now, sent as `sessions://changed` whenever one opens
 * or closes (each is a game window's).
 */
export type SessionsChanged = { sessions: Array<SessionId>, };
