// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One side's clock.
 */
export type SideClockView = { timeControl: string, moveTimeMs: number, reserveMs: number, };
