// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One side's clock.
 */
export type SideClockView = { timeControl: string, moveTimeMs: number, reserveMs: number, 
/**
 * The time this side has for a turn from its start: move time plus
 * reserve, within the time control's turn limit (the setup's minute
 * included). The UI colors the clock by it.
 */
turnAllowanceMs: number, };
