// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Board square, 0 = a1, 7 = h1, 56 = a8, 63 = h8.
 * Serializes as its index.
 */
export type Square = number;
