// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A server bot started: what the server answered, and the game the bot
 * opened, once it shows in the open games.
 */
export type StartedBotView = { 
/**
 * The text of the server's answer.
 */
message: string, 
/**
 * The game's gameroom id; none if it didn't show in time.
 */
gid: string | null, 
/**
 * Whether that game is rated.
 */
rated: boolean, };
