// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Square } from "./Square";
import type { StepKind } from "./StepKind";

export type StepTarget = { to: Square, 
/**
 * `None` for setup swaps.
 */
kind: StepKind | null, 
/**
 * Steps the piece needs to get there (more than 1 for a multi-step route).
 */
steps: number, };
