// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How a step fits into the turn.
 */
export type StepKind = "simple" | "pushStart" | "pushFinish" | "pullFinish";
