// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An engine Howdah suggests, by the URL of its newest manifest.
 */
export type SuggestedEngine = { name: string, url: string, };
