// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Color } from "./Color";

/**
 * A takeback request in a game on a server.
 */
export type TakebackView = { 
/**
 * The side asking.
 */
by: Color, 
/**
 * Whether the server shows the request (the user's has reached it).
 */
shown: boolean, 
/**
 * The user's answer to the opponent's request, while it's on its way.
 */
answer: boolean | null, };
