// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Square } from "./Square";
import type { TurnStepView } from "./TurnStepView";

export type TurnView = { steps: Array<TurnStepView>, stepsLeft: number, 
/**
 * Square a pushing piece must step into, if a push is under way.
 */
pushPending: Square | null, 
/**
 * Why the turn can't be committed yet, or `None` if it can.
 */
commitBlocker: string | null, };
