// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WatchState } from "./WatchState";

/**
 * A session following an arimaa.com game, sent as `gameroom://watch`
 * whenever it changes. (The server doesn't show spectators the game's
 * chat.)
 */
export type WatchView = { gid: string, state: WatchState, detail: string | null, 
/**
 * Whether the seat is an ASIP viewer seat, which the server sends
 * moves to only every ~10 s.
 */
delayed: boolean, 
/**
 * The game's permanent arimaa.com id, once it has ended and the
 * server has given one.
 */
finishedId: string | null, };
