// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChatLineView } from "./ChatLineView";
import type { Color } from "./Color";
import type { WatchState } from "./WatchState";

/**
 * A session following an arimaa.com game, sent as `gameroom://watch`
 * whenever it changes. (The server doesn't show spectators the game's
 * chat.)
 */
export type WatchView = { gid: string, state: WatchState, detail: string | null, 
/**
 * Whether the seat is an ASIP viewer seat, which the server sends
 * moves to only every ~10 s.
 */
delayed: boolean, 
/**
 * The game's permanent arimaa.com id, once it has ended and the
 * server has given one.
 */
finishedId: string | null, 
/**
 * The server's name for the game ("Casual game", a tournament round).
 */
event: string | null, 
/**
 * The user's side, when they play the game rather than watch it.
 */
side: Color | null, 
/**
 * Whether it's a postal game (moves days apart).
 */
postal: boolean, 
/**
 * Whether gold and silver have left the table (the server says so;
 * their clocks keep running).
 */
away: [boolean, boolean], 
/**
 * Whether the user's seat waits for an opponent to sit down. Their
 * first move is held until then.
 */
waiting: boolean, 
/**
 * Why the server refused the user's last move, until a move goes
 * through.
 */
refused: string | null, 
/**
 * The game's chat, oldest first (players get it; spectators don't).
 */
chat: Array<ChatLineView>, };
