// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How a game ended. The first three come from the position; the rest
 * are decided outside the rules (clocks, players, controllers).
 */
export type WinReason = "goal" | "elimination" | "immobilization" | "timeout" | "resignation" | "illegalMove" | "score" | "forfeit";
